apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -prd
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: esquire-deployment
  - path: service-patch.yaml
    target:
      kind: Service
      name: esquire-service
