apiVersion: v1
kind: Service
metadata:
  name: esquire-service
spec:
  selector:
    app: esquire-deployment
  ports:
    - protocol: TCP
      name: http
      port: 80  # The port you want to expose externally (outside the cluster)
      targetPort: 8072
  type: NodePort
