apiVersion: apps/v1
kind: Deployment
metadata:
  name: esquire-microservice
  labels:
    app: esquire-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esquire-microservice
  template:
    metadata:
      labels:
        app: esquire-microservice
    spec:
      containers:
      - name: esquire-microservice
        image: zx8086/esquire-microservice:7
        ports:
        - containerPort: 8072